---
title: "CSS Selector Examples"
author: "Clay Ford"
date: "Spring 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These examples are courtesy of the excellent tutorial at http://flukeout.github.io/. See `help(html_nodes)` for more information on CSS selector support in the `rvest` package.

- `div` selects all `<div>` elements
- `p` selects all `<p>` elements

- `#cool` selects any element with `id="cool"`
- `ul#long` selects all `<ul>` elements that have `id="long"`

- `p strong` selects all `<strong>` elements that are inside of any `<p>`
- `#fancy span` selects any `<span>` elements that are inside of the element with `id="fancy"`

- `.neato` selects all elements with `class="neato"`

- `ul.important` selects all `<ul>` elements that have `class="important"`
- `#big.wide` selects all elements with `id="big"` that also have `class="wide"`

- `p, .fun` selects all `<p>` elements as well as all elements with `class="fun"`
- `a, p, div` selects all `<a>`, `<p>` and `<div>` elements

- `p *` selects any element inside all `<p>` elements

- `ul.fancy *` selects every element inside all `<ul class="fancy">` elements

- `p + .intro` selects every element with `class="intro"` that directly follows a `<p>`
- `div + a` selects every `<a>` element that directly follows a `<div>`


- `A ~ B` selects all `B` that follow an `A`

- `A > B` selects all `B` that are direct children `A`

- `p:first-child` selects all first child `<p>` elements
- `div p:first-child` selects all first child `<p>` elements that are in a `<div>`

- `span:only-child` selects the `<span>` elements that are the only child of some other element
- `ul li:only-child` selects the only `<li>` element that are in a `<ul>`
- `:last-child` selects all last-child elements
- `span:last-child` selects all last-child `<span>` elements
- `ul li:last-child` selects the last `<li>` elements inside of any `<ul>`

- `:nth-child(8)` selects every element that is the 8th child of another element
- `div p:nth-child(2)` selects the second `<p>` in every `<div>`

- `:nth-last-child(2)` selects all second-to-last child elements

- `span:first-of-type` selects the first `<span>` in any element

- `div:nth-of-type(2)` selects the second instance of a `<div>`
- `.example:nth-of-type(odd)` selects all odd instances of `class="example"`

- `span:nth-of-type(6n+2)` selects every 6th instance of a `<span>`, starting from (and including) the second instance

- `p span:only-of-type` selects a `<span>` within any `<p>` if it is the only `<span>` in there

- `div:last-of-type` selects the last `<div>` in every element
- `p span:last-of-type` selects the last `<span>` in every `<p>`

- `div:empty` selects all empty `<div>` elements

- `:not(#fancy)` selects all elements that do not have `id="fancy"`
- `div:not(:first-child)` selects every `<div>` that is not a first child
- `:not(.big, .medium)` selects all elements that do not have `class="big"` or `class="medium"`

- `a[href^='https']` selects all `<a>` elements with href attribute value beginning with `"https"`
- `[type]` selects all elements that have a `type=` attribute

- `[value]` selects all elements that have a `value=` attribute
- `input[disabled]` selects all input elements with the `disabled` attribute

- `input[type='checkbox']` selects all `checkbox` input elements

- `.toy[category^='Swim']` selects elements with `class="toy"` and either `category="Swimwear` or `category="Swimming"`

- `img[src$='.jpg']` selects all `.jpg` images

- `img[src*='/thumbnails/']` selects all image elements that show images from the `"thumbnails"` folder
- `[class*='heading']` selects all elements with `"heading"` in their class, like `class="main-heading"` and `class="sub-heading"`
